on:
  push:
    branches:
    - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    #- uses: docker://texlive/texlive:TL2021-historic
    #  with:
    #    args: sh -c "apt-get update && apt-get install -y file fonts-liberation zip && ./makehtml.sh"
    #- run: sudo apt-get update && sudo apt-get install -y fonts-liberation texlive-full && ./makehtml.sh
    - run: docker build . && docker cp "$(docker create "$(docker build -q .)")":/artifacts .
    - uses: JamesIves/github-pages-deploy-action@4.1.8
      with:
        branch: gh-pages
        folder: artifacts
